RecommendationWebApplication/Models/ErrorViewModel.cs
using System;

namespace RecommendationWebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RecommendationWebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RecommendationWebApplication.Models;

namespace RecommendationWebApplication.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RecommendationWebApplication/Controllers/LastVisitedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RecommendationWebApplication.Controllers
{
    public class LastVisitedController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RecommendationWebApplication/Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RecommendationWebApplication.Controllers
{
    public class OffersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RecommendationWebApplication/Controllers/RecommendationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RecommendationWebApplication.Controllers
{
    public class RecommendationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RecommendationWebApplication/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

RecommendationWebApplication/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RecommendationWebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@section scripts{
    <script src="~/js/home.js" asp-append-version="true"></script>
}


@section Styles {
    <link rel="stylesheet" href="~/css/home.css" type="text/css" />
}

<div class="container">
    <div class="row">
        <div class="col col-md-4">
            <div class="item" profile="gaming">
                <img src="~/images/gaming_photo.jpg" />
                <div>Gaming series</div>
            </div>
        </div>
        <div class="col col-md-4">
            <div class="item" profile="office">
                <img src="~/images/office_photo.jpg" />
                <div>Office series</div>
            </div>

        </div>
        <div class="col col-md-4">
            <div class="item" profile="student">
                <img src="~/images/school_photo.jpg" />
                <div>School series</div>
            </div>

        </div>
    </div>
</div>

RecommendationWebApplication/Views/Home/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecommendationWebApplication</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/Font-Awesome/web-fonts-with-css/css/fontawesome-all.min.css" />
        <link rel="stylesheet" href="~/css/preloader.css" type="text/css" />
        <link rel="stylesheet" href="~/css/site.css" />
        @RenderSection("Styles", required: false)

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/cookie/cookie.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

RecommendationWebApplication/Views/LastVisited/Index.cshtml
@{
    ViewData["Title"] = "Last Visited";
}

@section scripts{
    <script src="~/js/paginationManager.js" asp-append-version="true"></script>
    <script src="~/js/lastVisited.js" asp-append-version="true"></script>
}


@section Styles {
    <link rel="stylesheet" href="~/css/lastVisited.css" type="text/css" />
}

<div class="visitedContainer">

</div>
<br/>

RecommendationWebApplication/Views/Offers/Filters.cshtml
<div class="filtersRealContainer">
    <div class="title">
        Filters
    </div>

    <div class="filter price">
        <div class="filterTitle">
            Price range
        </div>
        <div class="filterValues">
            <div class="priceSlider"></div>
        </div>
    </div>

    <div class="filter processorSeries">
        <div class="filterTitle">
            Processor series
        </div>
        <div class="filterValues">
            <select class="form-control">
                <option value="*">*</option>
                <option value="Intel Core i3">intel Core i3</option>
                <option value="Intel Core i5">intel Core i5</option>
                <option value="Intel Core i7">intel Core i7</option>
                <option value="other">other</option>
            </select>
        </div>
    </div>

    <div class="filter diskType">
        <div class="filterTitle">
            Disk type
        </div>
        <div class="filterValues">
            <select class="form-control">
                <option value="*">*</option>
                <option value="HDD">HDD</option>
                <option value="SSD">SSD</option>
                <option value="SSD + HDD">SSD + HDD</option>
                <option value="other">other</option>
            </select>
        </div>
    </div>

    <div class="filter matrixResolution">
        <div class="filterTitle">
            Matrix resolution
        </div>
        <div class="filterValues">
            <select class="form-control">
                <option value="*">*</option>
                <option value="1366 x 768">1366 x 768 (HDR)</option>
                <option value="1600 x 900">1600 x 900</option>
                <option value="1920 x 1080">1920 x 1080 (FHD)</option>
                <option value="3840 x 2160">3840 x 2160 (4K)</option>
                <option value="other">other</option>
            </select>
        </div>
    </div>

    <div class="filter minDiskSize">
        <div class="filterTitle">
            Minimum disk size
        </div>
        <div class="filterValues">
            <div class="input-group">
                <input class="form-control" />
                <div class="input-group-append">
                    <span class="input-group-text" id="basic-addon1">GB</span>
                </div>
            </div>
        </div>
    </div>

    <div class="filter minRamSize">
        <div class="filterTitle">
            Minimum RAM size
        </div>
        <div class="filterValues">
            <div class="input-group">
                <input class="form-control" />
                <div class="input-group-append">
                    <span class="input-group-text" id="basic-addon1">GB</span>
                </div>
            </div>
        </div>
    </div>

    <div class="buttonContainer">
    </div>
</div>

RecommendationWebApplication/Views/Offers/Index.cshtml
@{
    ViewData["Title"] = "Offers";
}

@section Styles {
    <link rel="stylesheet" href="~/css/offers.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/jq-range-slider/css/iThing.css" />
}


@section scripts{
    <script src="~/js/paginationManager.js" asp-append-version="true"></script>
    <script src="~/js/offersManager.js" asp-append-version="true"></script>

    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/jq-range-slider/dest/jQEditRangeSlider-min.js" asp-append-version="true"></script>
}
<div class="row">
    <div class="col-6 col-md-3">
        <div class="filtersContainer">
            @await Html.PartialAsync("Filters")
        </div>
    </div>

    <div class="col-12 col-md-9 offersContainer">
    </div>
</div>
<div class="row mt paginationRow">
    <div class="col-6 col-md-3">
    </div>

    <div class="col-12 col-md-9 paginationContainer">
    </div>
</div>

RecommendationWebApplication/Views/Recommendation/Index.cshtml
@{
    ViewData["Title"] = "Recommendation";
}

@section scripts{
    <script src="~/js/recommendation.js" asp-append-version="true"></script>
}


@section Styles {
    <link rel="stylesheet" href="~/css/recommendation.css" type="text/css" />
}

<div class="recommendationContainer">
    <div class="usersRecommendation">
        <section class="carousel slide" data-ride="userCarousel" id="postsCarousel">
            <div class="row arrows">
                <div class="col text-left">
                    <h2>Other users also saw</h2>
                </div>
                    <div class="col text-right">
                        <a class="btn btn-outline-secondary prev" href="" title="go back"><i class="fa fa-lg fa-chevron-left"></i></a>
                        <a class="btn btn-outline-secondary next" href="" title="more"><i class="fa fa-lg fa-chevron-right"></i></a>
                    </div>
                </div>
        </section>
        <section class="carousel slide" data-ride="userCarousel" id="postsCarousel">
            <div class="p-t-0 m-t-2 carousel-inner">
            </div>
        </section>
    </div>
    <div class="profileRecommendation">
        <section class="carousel slide" data-ride="carousel" id="postsCarousel">
            <div class="row arrows">
                <div class="col text-left">
                    <h2>Offers that may interest you</h2>
                </div>
                <div class="col text-right">
                    <a class="btn btn-outline-secondary prev" href="" title="go back"><i class="fa fa-lg fa-chevron-left"></i></a>
                    <a class="btn btn-outline-secondary next" href="" title="more"><i class="fa fa-lg fa-chevron-right"></i></a>
                </div>
            </div>
</section>
        <section class="carousel slide" data-ride="carousel" id="postsCarousel">
            <div class="p-t-0 m-t-2 carousel-inner">
            </div>
        </section>
    </div>
</div>

RecommendationWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecommendationWebApplication</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/jquery-ui/themes/ui-darkness/jquery-ui.min.css">
        <link rel="stylesheet" href="~/lib/Font-Awesome/web-fonts-with-css/css/fontawesome-all.min.css" />
        <link rel="stylesheet" href="~/css/preloader.css" type="text/css" />
        <link rel="stylesheet" href="~/css/site.css" />
        @RenderSection("Styles", required: false)

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="header-content">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">RecommendationWebApplication</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Offers", "Index", "Offers", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Recommendation", "Index", "Recommendation", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Last visited", "Index", "LastVisited", null, new { @class = "nav-link" })</li>
                </ul>
                <span class="navbar-text">
                </span>
            </div>
        </nav>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - RecommendationWebApplication</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        @*<script src="~/lib/jquery-ui/jquery-ui.min.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/cookie/cookie.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>